api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "cart-transform-extension"
type = "function"
uid = "0404f2f6-8f30-58e6-8447-1f3dfe202611d81439c8"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart_transform_run"

  [extensions.build]
  command = "cargo build --target=wasm32-unknown-unknown --release"
  path = "target/wasm32-unknown-unknown/release/cart-transform-extension.wasm"
  watch = [ "src/**/*.rs" ]

  [extensions.ui.paths]
  create = "/"
  details = "/"
