api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "cart-validation-extension"
type = "function"
uid = "c7bbe079-b564-8d95-359d-0553cbfc1b860b73e078"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.validations.generate.run"
  input_query = "src/cart_validations_generate_run.graphql"
  export = "cart_validations_generate_run"

  [extensions.build]
  command = "cargo build --target=wasm32-unknown-unknown --release"
  path = "target/wasm32-unknown-unknown/release/cart-validation-extension.wasm"
  watch = ["src/**/*.rs"]
